# Generated by Django 3.2.18 on 2023-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20230419_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quizzes.Question', verbose_name='Вопросы'),
        ),
    ]
